### ISSUE TITLE
HTML URL encoding with special characters is not accepted to create link in GSheets or GDrive or other apps

### ISSUE THREAD

**Issue by ariadnamorales** [pch-innovations/gdrive-finder-service#1] opened 2023-04-26 15:53 UTC
Hi, thank you for developing and sharing this tool. I am using it, and it works, but not in some apps. For example, when I paste the GDrive link in GSheets or GDocs and try to create a link, I get the error that the URL is invalid. I think it is because of the special characters, such as %40 encoding @ and %20 for space. Do you have a tip on how to solve this?

**Comment by dotKokott** [comment] 2023-05-03 08:58
Hello!

I investigated the issue and the problem is that google apps only allow you to create **web** links (http://, https://). Our link is a an **app** link (app://).

There is one way to solve this for you individually. There is a browser extension called [REDIRECTOR](https://einaregilsson.com/redirector/). It allows you to create custom rewrites for you browser.

You can create a rule that replaces "http://gdrive/*" with "gdrive://". So when adding a link to your document you just replace "gdrive://" with "http://gdrive/" and it will create a valid link. When you click on that link the REDIRECTOR extension will rewrite it to our app link.

Here is an example configuration on how to configure REDIRECTOR to do that:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/503388/235872155-e476dc88-cd8a-4f92-acbf-50285b69716a.png">

**Comment by dotKokott** [comment] 2023-05-03 09:06
Closing this issue as "not planned" as we will not be able to generate a link that google apps will currently accept as a valid web link. This might change in the future.

**Closed by dotKokott** 2023-05-03 09:06 UTC
Labels: question
